### ISSUE TITLE
Help to compile in Windows 10

### ISSUE THREAD

**Issue by paulo-correia** [SegiH/Asbru-CM-Runner#1]
Hi, 

I´m tring to compile with Visual Studio 2019
Getting error on Program.cs
Error code: 0x80004005

Can you help?

**Comment by SegiH** [comment]
I also use VS 2019. I just opened the project in VS 2019 and was able to compile it.

Does the error give you any additional info to let you know what went wrong ?

**Comment by SegiH** [comment]
Are you still having a problem compiling my app or can I close this issue ?

**Comment by SegiH** [comment]
I am closing this issue because of a lack of response. If you are still having this issue, I can reopen it.
