### ISSUE TITLE
Installation instructions doubt

### ISSUE THREAD

**Issue by mguare** [SegiH/Asbru-CM-Runner#2]
Hi Segi,

Thanks a lot for this work. 
I'm trying to install your runner in order to use Asbru in W10, but I don't know where I need to put these files (correct path).

Could you please specify that?

Thanks.

**Comment by SegiH** [comment]
Hi,

I just tested out my app a few seconds ago. I downloaded the zip from the Releases and unzipped it in the downloads folder and ran the exe. This assumes that XMing is installed in the default location.

**Comment by SegiH** [comment]
Closed due to lack of response. As a side note, if you use Windows 11, when you enable WSL2 you will get GUI support without having to install XMing.
