### ISSUE TITLE
Please clarify the asbru-cm-runner instructions

### ISSUE THREAD

**Issue by jorgemiguelsilvestre** [SegiH/Asbru-CM-Runner#4]
How can I run the runner code, can you pleae clarify?
I have problems in display export too...

**Comment by SegiH** [comment]
Hi

You would need to build the runner app in Visual Studio or download the latest release from the Releases section.

Have you done that already ?

**Comment by SegiH** [comment]
I am closing this issue since there has been no response.

The instructions to build the code from source is in the README or if you do not want to build the source, you can download a zip file with a Windows executable from the Releases
