### ISSUE TITLE
Something to add to the docs

### ISSUE THREAD

**Issue by rudolfbyker** [SegiH/Asbru-CM-Runner#5]
If you installed Docker Desktop before doing "wsl --install -d ubuntu" for the first time, then you will have the situation where running `wsl` or `bash` simply does nothing. This happens because `docker-desktop-data` is the default instead of `ubuntu`.

```powershell
wsl --list --all --verbose
```

```
  NAME                   STATE           VERSION
* docker-desktop         Stopped         2
  docker-desktop-data    Stopped         2
  Ubuntu                 Stopped         1
```

The fix is to set the default to `ubuntu`:

```powershell
wsl --set-default Ubuntu
```

```powershell
wsl --list --all --verbose
```

```
  NAME                   STATE           VERSION
* Ubuntu                 Stopped         1
  docker-desktop         Stopped         2
  docker-desktop-data    Stopped         2
```

Solution credit goes to https://superuser.com/questions/1661596/wsl-doesnt-want-to-launch

**Comment by SegiH** [comment]
Thanks. I added this to the docs
