### ISSUE TITLE
Avoid installing Xming (or any other X Window System) and use WSLg?

### ISSUE THREAD

**Issue by C-Duv** [SegiH/Asbru-CM-Runner#6]
With WSL 2, an X Window System is shipped with Windows: [WSLg](https://github.com/microsoft/wslg) and it works fine with Ásbrú CM.

Can the code be updated to use WSLg (via an option maybe)?

**Comment by SegiH** [comment]
I can probably update the code to run without XMing if the version of WSL is version 2 but I will probably make my program check the WSL version and automatically run it without XMing if the WSL version is 2 so you don't need to specify that

**Comment by s1dh** [comment]
Hello, is there any ETA regarding this update ? It would be great to use WSLg with Ásbrú CM

**Comment by SegiH** [comment]
Let me look into this further.  I haven't forgotten about your request

**Comment by SegiH** [comment]
@s1dh 

I am looking at the code to add this ability. It seems there's a bit of an obstacle. The WSL version you use is specific to the distro. I named my distro Ubuntu but I believe you can name it anything so if I want to check if you are using WSL 1 or 2, I'd have to assume some things.

What do you think of me adding a feature where I add a command line parameter that you use when you launch asbru-cm-launcher so you You would run my app with "asbru-cm-launcher --skip-xming" and it will launch Asbru CM without trying to launch XMing

**Comment by SegiH** [comment]
@C-Duv, @s1dh 

Sorry it took so long to get around to adding this feature but I just published version 1.2 that does not require XMing when using WSL 2.

Please test it out and open an issue on Github if you encounter any problems.
